# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- source

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'
- script: |
    git config user.email "gqlx@florian-rappl.de" 
    git config user.name "Florian Rappl"
    npm install
    npm run deploy -- -r https://$(variables.github_pat)@github.com/graphql-extended/graphql-extended.github.io.git
  displayName: 'npm install and build'
